## Aplicar as técnicas seguintes:

•	Random Forest (RF) 

•	ExtraTreesClassifier (ETC)

•	XGBoost (XGB) com Early Stopping

•	Gaussian Naive Bayes


## Preparando os dados para treinar

In [22]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np

from sklearn import metrics

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier

from sklearn.naive_bayes import GaussianNB

from xgboost.sklearn import XGBClassifier

## importando os dataframes para treino

In [23]:
df1 = pd.read_csv('/content/drive/Shared drives/iniciacao_cientifica_2019_2020/dataframes_treino/turma_102_2016_1/Dataframe1_Turma_102_2016_06_07_12_00_00_2016_06_30_11_55_00.csv', sep=';')

In [24]:
df_target_user = pd.read_csv('/content/drive/Shared drives/iniciacao_cientifica_2019_2020/csv_datasets/usuarios_classificados.csv')

## Criando um merge entre o df_target_user e df1

In [25]:
df_target_user = df_target_user[['semester_id', 'class_id', 'user_id', 'target']]

In [26]:
df1_data_target = pd.merge(df1, df_target_user, on=['semester_id', 'class_id', 'user_id'], how='inner')

In [27]:
df1_data_target.drop(['semester_id', 'class_id', 'user_id'], axis=1, inplace=True)

In [28]:
df1_data_target

number_logins  ...          target
0               6  ...      Desistente
1              13  ...      Desistente
2              21  ...  Não Desistente
3               8  ...      Desistente
4               8  ...      Desistente
5              13  ...  Não Desistente
6              13  ...  Não Desistente
7              19  ...  Não Desistente
8              21  ...  Não Desistente
9              28  ...  Não Desistente
10              6  ...  Não Desistente
11             22  ...  Não Desistente
12              0  ...      Desistente
13             12  ...  Não Desistente
14             19  ...  Não Desistente
15             24  ...  Não Desistente
16             32  ...  Não Desistente
17             15  ...  Não Desistente
18             18  ...  Não Desistente
19             13  ...  Não Desistente
20             30  ...  Não Desistente
21             12  ...  Não Desistente
22             16  ...  Não Desistente
23              7  ...  Não Desistente
24             20  ...  Não Desistente
25             18  ...  Não Desistente
26             10  ...  Não Desistente
27             19  ...  Não Desistente
28             21  ...  Não Desistente
29             17  ...  Não Desistente
30             16  ...  Não Desistente
31             14  ...  Não Desistente
32             19  ...      Desistente
33             13  ...      Desistente
34             26  ...  Não Desistente
35             16  ...  Não Desistente
36             15  ...  Não Desistente
37              0  ...      Desistente
38             23  ...  Não Desistente
39             13  ...  Não Desistente
40             23  ...  Não Desistente
41             17  ...  Não Desistente
42             16  ...  Não Desistente
43             17  ...  Não Desistente
44             21  ...      Desistente
45             14  ...  Não Desistente
46             23  ...  Não Desistente
47             20  ...  Não Desistente
48              9  ...      Desistente
49              3  ...      Desistente
50             33  ...  Não Desistente
51              7  ...  Não Desistente
52             10  ...  Não Desistente

[53 rows x 17 columns]

## Preparando para treinar os dados até a primeira avaliação

In [29]:
# pegando as colunas de features
features = df1_data_target.columns.difference(['target'])

# dados de treino
X = df1_data_target[features].values

# classe target
y = df1_data_target['target'].values

## Dividindo uma parte para teste e outra para treino

In [30]:
# dividindo uma parte dos dados para treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [31]:
# verificando a forma dos dados de treino
X_train.shape, y_train.shape

((35, 16), (35,))

In [32]:
# verificando a forma dos dados de teste
X_test.shape, y_test.shape

((18, 16), (18,))

## Utilizando um GridSearchCV e RandomForestClassifier para encontrar os melhores parâmetros

In [33]:
# criando uma instância de RFC
classifier_rf = RandomForestClassifier()

# parâmetros para o gridsearchcv
param_grid_ = {
    "criterion": ['entropy', 'gini'],
    "n_estimators": [25, 50, 75],
    "bootstrap": [False, True],
    "max_depth": [3, 5, 10]
} 

# criando uma instância do gridsearchcv
grid_search = GridSearchCV(
    estimator=classifier_rf, 
    param_grid=param_grid_, 
    scoring="accuracy", 
    cv=5
)

# treinando com o gridsearch
grid_search.fit(X_train, y_train)

# atrinbuindo o modelo
classifier_rf = grid_search.best_estimator_ 

print(grid_search.best_params_, grid_search.best_score_)

{'bootstrap': False, 'criterion': 'entropy', 'max_depth': 3, 'n_estimators': 25} 0.9428571428571428


In [34]:
# classificando o conjunto de teste
y_predict = grid_search.predict(X_test)

# metricas de avaliação de desempenho
print(metrics.classification_report(y_test, y_predict))

# matrix de confusão
print(metrics.confusion_matrix(y_test, y_predict))

                precision    recall  f1-score   support

    Desistente       1.00      1.00      1.00         5
Não Desistente       1.00      1.00      1.00        13

      accuracy                           1.00        18
     macro avg       1.00      1.00      1.00        18
  weighted avg       1.00      1.00      1.00        18

[[ 5  0]
 [ 0 13]]


## Encontrando os melhores parâmetros com GridSearch o ExtraTreesClassifier

In [35]:
# criando uma instância de ETC
classifier_et = ExtraTreesClassifier()

# parametros para o gridsearchcv
param_grid_ = {
    "criterion": ['entropy', 'gini'],
    "n_estimators": [25, 50, 75],
    "bootstrap": [False, True],
    "max_depth": [3, 5, 10]
} 

# criando uma instância de gridsearchcv
grid_search = GridSearchCV(
    estimator=classifier_et, 
    param_grid = param_grid_, 
    scoring="accuracy", 
    cv=5
)

# treinando com os dados de treino
grid_search.fit(X_train, y_train)

# atribuindo a instância os melhores parâmetros
classifier_et = grid_search.best_estimator_ 

print(grid_search.best_params_, grid_search.best_score_)

{'bootstrap': False, 'criterion': 'entropy', 'max_depth': 3, 'n_estimators': 25} 0.9428571428571428


In [36]:
# classificando o conjunto de teste
y_predict = grid_search.predict(X_test)

# metricas de avaliação de desempenho
print(metrics.classification_report(y_test, y_predict))

# matrix de confusão
print(metrics.confusion_matrix(y_test, y_predict))

                precision    recall  f1-score   support

    Desistente       0.75      0.60      0.67         5
Não Desistente       0.86      0.92      0.89        13

      accuracy                           0.83        18
     macro avg       0.80      0.76      0.78        18
  weighted avg       0.83      0.83      0.83        18

[[ 3  2]
 [ 1 12]]


## XGB e GridSearchCV para encontrar os melhores parâmetros

### Parâmetros
**num_boost_rounds:** corresponde ao número de rodadas de aumento ou árvores a serem construídas.

**early_stopping_round:** verifica se nas N primeiras rodadas o algoritmo melhora, caso não melhore ele para e fica com a melhor rodada. É nessário usar o **eval_set**

**eval_set:** (list, opcional) - Uma lista de pares de tuplas (X, y) a serem usados ​​como conjuntos de validação, para os quais as métricas serão calculadas. As métricas de validação nos ajudarão a acompanhar o desempenho do modelo.

**max_depth:** é o número máximo de nós permitido da raiz até a folha mais distante de uma árvore.

**min_child_weight:** é o peso mínimo (ou número de amostras, se todas as amostras tiverem um peso de 1) necessário para criar um novo nó na árvore.

**subsample:** corresponde à fração de observações (as linhas) para subamostra em cada etapa. Por padrão, é definido como 1, o que significa que usamos todas as linhas.

**colsample_bytree:** corresponde à fração de recursos (as colunas) a serem usadas. Por padrão, é definido como 1, o que significa que usaremos todos os recursos.

**ETA:** controla a taxa de aprendizado. (com um eta mais baixo, precisamos de mais rodadas de reforço)

In [37]:
# instanciando o xgbclassifier com algumas características
classifier_xgb = XGBClassifier(
    objective= 'binary:logistic',
    nthread=4,
    seed=42
)

# setando os parâmetros usados no grid
parameters = {
    'max_depth': range (2, 10, 1),
    'n_estimators': range(60, 220, 40),
    'learning_rate': [0.1, 0.01, 0.05]
}

# setando os parâmetros do GridSearchCV
grid_search = GridSearchCV(
    estimator=classifier_xgb,
    param_grid=parameters,
    scoring = 'accuracy',
    n_jobs = 10,
    cv = 10,
    # verbose=True
)

fit_params={
    'early_stopping_rounds':10,
    'eval_set': [(X_test, y_test)],
    'verbose':True
}

# treinando com o melhor estimator
grid_search.fit(
    X_train, 
    y_train,
    **fit_params
)

# atribuindo a instância os melhores parâmetros
classifier_xgb = grid_search.best_estimator_ 

print(grid_search.best_params_, grid_search.best_score_)

[0]	validation_0-error:0.055556
Will train until validation_0-error hasn't improved in 10 rounds.
[1]	validation_0-error:0.055556
[2]	validation_0-error:0.055556
[3]	validation_0-error:0.055556
[4]	validation_0-error:0.055556
[5]	validation_0-error:0.055556
[6]	validation_0-error:0.055556
[7]	validation_0-error:0.055556
[8]	validation_0-error:0.055556
[9]	validation_0-error:0.055556
[10]	validation_0-error:0.055556
Stopping. Best iteration:
[0]	validation_0-error:0.055556

{'learning_rate': 0.1, 'max_depth': 2, 'n_estimators': 60} 0.8666666666666666


In [38]:
# classificando o conjunto de teste
y_predict = grid_search.predict(X_test)

# metricas de avaliação de desempenho
print(metrics.classification_report(y_test, y_predict))

# matrix de confusão
print(metrics.confusion_matrix(y_test, y_predict))

                precision    recall  f1-score   support

    Desistente       1.00      0.80      0.89         5
Não Desistente       0.93      1.00      0.96        13

      accuracy                           0.94        18
     macro avg       0.96      0.90      0.93        18
  weighted avg       0.95      0.94      0.94        18

[[ 4  1]
 [ 0 13]]


## Aplicando *Gaussian Naive Bayes* no conjunto de treinamento

In [39]:
# instânciando um GaussianNB
classifier_gnb = GaussianNB()

# treinando o modelo
classifier_gnb.fit(X_train, y_train)


GaussianNB(priors=None, var_smoothing=1e-09)

In [40]:
# classificando o conjunto de teste
y_predict = classifier_gnb.predict(X_test)

# metricas de avaliação de desempenho
print(metrics.classification_report(y_test, y_predict))

# matrix de confusão
print(metrics.confusion_matrix(y_test, y_predict))

                precision    recall  f1-score   support

    Desistente       1.00      0.80      0.89         5
Não Desistente       0.93      1.00      0.96        13

      accuracy                           0.94        18
     macro avg       0.96      0.90      0.93        18
  weighted avg       0.95      0.94      0.94        18

[[ 4  1]
 [ 0 13]]


## Salvando os modelos

In [41]:
from joblib import dump, load

In [42]:
#dump(classifier_rf, '/content/drive/Shared drives/iniciacao_cientifica_2019_2020/modelos/2016_1_102_df1/classifier_rf.joblib')
#dump(classifier_et, '/content/drive/Shared drives/iniciacao_cientifica_2019_2020/modelos/2016_1_102_df1/classifier_et.joblib')
#dump(classifier_xgb, '/content/drive/Shared drives/iniciacao_cientifica_2019_2020/modelos/2016_1_102_df1/classifier_xgb.joblib')
#dump(classifier_gnb, '/content/drive/Shared drives/iniciacao_cientifica_2019_2020/modelos/2016_1_102_df1/classifier_gnb.joblib')